/**:
  ros__parameters:
    uav_parameters:
      mass: 0.027                  # Kg
      arm_length: 0.046            # m
      num_of_arms: 4
      inertia:                     # Kg.m^2
        x: 16.571710e-6
        y: 16.571710e-6
        z: 29.261652e-6
      moment_constant: 5.964552e-03 # m
      thrust_constant: 1.317927e-07 # N.s^2/rad^2
      max_rotor_speed: 1000         # rad/s
      gravity: 9.8066               # m/s^2
      omega_to_pwm_coefficient:
        x_2: 0.001142
        x_1: 0.2273
        x_0: 914.2
      PWM_MIN: 1075
      PWM_MAX: 1950
      input_scaling: 1000
      zero_position_armed: 0