/**:
  ros__parameters:    
    # ArUco detector parameters
    perception:
      aruco_detector:
        tag_dictionary: "DICT_4X4_250"
        tag_ids: [0]
        plate_size_m: 0.60
        publish_debug: true
        overlay.show: true
        overlay.base_is_frd: true
        camera_optical_frame: "drone/camera_optical_frame"
        parent_frame: "drone/base_link"
        child_frame: "rover/base_link"
