/**:
  ros__parameters:
    sitl_mode: true # not used
    control_mode: 1 # not used
    topics_names:
      command_pose_topic: "command/pose"
      command_traj_topic: "command/trajectory"
      control_command_topic: "command/control"
      target_state_topic: "target/odometry"
      nav_state_topic: "navigation/state"
      odometry_topic: "fmu/out/vehicle_odometry"
      status_topic: "fmu/out/vehicle_status_v1"
      battery_status_topic: "fmu/out/battery_status"
      actuator_status_topic: "fmu/out/actuator_motors"
      offboard_control_topic: "fmu/in/offboard_control_mode"
      vehicle_command_topic: "fmu/in/vehicle_command"
      vehicle_command_ack_topic: "fmu/in/vehicle_command_ack"
      attitude_setpoint_topic: "fmu/in/vehicle_attitude_setpoint_v1"
      thrust_setpoints_topic: "fmu/in/vehicle_thrust_setpoint"
      torque_setpoints_topic: "fmu/in/vehicle_torque_setpoint"
      actuator_control_topic: "fmu/in/actuator_motors"
      mocap_topic: "fmu/in/vehicle_mocap_odometry"