/**:
  ros__parameters:
    mpc_parameters:
        N: 15
        horizon: 1.5
        frequency: 100.0
        Q: [40.0, 40.0, 40.0, 4.0, 4.0, 4.0, 2.0, 2.0, 2.0, 0.25, 0.25, 0.25]
        R: [0.1, 1.0, 1.0, 1.0]
    